[package]
name = "mfx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
hw_common = { path = "../hw_common" }

[build-dependencies]
cc = "1.0"
bindgen = "0.59"
